// All 48 teams (static for the whole tournament) — names match ESPN's feed.
// Embedded so the site only needs the network for live scores.
const TEAMS = [
  {"name": "Mexico", "group": "A", "flag": "https://flagcdn.com/w80/mx.png"},
  {"name": "South Africa", "group": "A", "flag": "https://flagcdn.com/w80/za.png"},
  {"name": "South Korea", "group": "A", "flag": "https://flagcdn.com/w80/kr.png"},
  {"name": "Czechia", "group": "A", "flag": "https://flagcdn.com/w80/cz.png"},
  {"name": "Canada", "group": "B", "flag": "https://flagcdn.com/w80/ca.png"},
  {"name": "Bosnia-Herzegovina", "group": "B", "flag": "https://flagcdn.com/w80/ba.png"},
  {"name": "Qatar", "group": "B", "flag": "https://flagcdn.com/w80/qa.png"},
  {"name": "Switzerland", "group": "B", "flag": "https://flagcdn.com/w80/ch.png"},
  {"name": "Brazil", "group": "C", "flag": "https://flagcdn.com/w80/br.png"},
  {"name": "Morocco", "group": "C", "flag": "https://flagcdn.com/w80/ma.png"},
  {"name": "Haiti", "group": "C", "flag": "https://flagcdn.com/w80/ht.png"},
  {"name": "Scotland", "group": "C", "flag": "https://flagcdn.com/w80/gb-sct.png"},
  {"name": "United States", "group": "D", "flag": "https://flagcdn.com/w80/us.png"},
  {"name": "Paraguay", "group": "D", "flag": "https://flagcdn.com/w80/py.png"},
  {"name": "Australia", "group": "D", "flag": "https://flagcdn.com/w80/au.png"},
  {"name": "Türkiye", "group": "D", "flag": "https://flagcdn.com/w80/tr.png"},
  {"name": "Germany", "group": "E", "flag": "https://flagcdn.com/w80/de.png"},
  {"name": "Curaçao", "group": "E", "flag": "https://flagcdn.com/w80/cw.png"},
  {"name": "Ivory Coast", "group": "E", "flag": "https://flagcdn.com/w80/ci.png"},
  {"name": "Ecuador", "group": "E", "flag": "https://flagcdn.com/w80/ec.png"},
  {"name": "Netherlands", "group": "F", "flag": "https://flagcdn.com/w80/nl.png"},
  {"name": "Japan", "group": "F", "flag": "https://flagcdn.com/w80/jp.png"},
  {"name": "Sweden", "group": "F", "flag": "https://flagcdn.com/w80/se.png"},
  {"name": "Tunisia", "group": "F", "flag": "https://flagcdn.com/w80/tn.png"},
  {"name": "Belgium", "group": "G", "flag": "https://flagcdn.com/w80/be.png"},
  {"name": "Egypt", "group": "G", "flag": "https://flagcdn.com/w80/eg.png"},
  {"name": "Iran", "group": "G", "flag": "https://flagcdn.com/w80/ir.png"},
  {"name": "New Zealand", "group": "G", "flag": "https://flagcdn.com/w80/nz.png"},
  {"name": "Spain", "group": "H", "flag": "https://flagcdn.com/w80/es.png"},
  {"name": "Cape Verde", "group": "H", "flag": "https://flagcdn.com/w80/cv.png"},
  {"name": "Saudi Arabia", "group": "H", "flag": "https://flagcdn.com/w80/sa.png"},
  {"name": "Uruguay", "group": "H", "flag": "https://flagcdn.com/w80/uy.png"},
  {"name": "France", "group": "I", "flag": "https://flagcdn.com/w80/fr.png"},
  {"name": "Senegal", "group": "I", "flag": "https://flagcdn.com/w80/sn.png"},
  {"name": "Iraq", "group": "I", "flag": "https://flagcdn.com/w80/iq.png"},
  {"name": "Norway", "group": "I", "flag": "https://flagcdn.com/w80/no.png"},
  {"name": "Argentina", "group": "J", "flag": "https://flagcdn.com/w80/ar.png"},
  {"name": "Algeria", "group": "J", "flag": "https://flagcdn.com/w80/dz.png"},
  {"name": "Austria", "group": "J", "flag": "https://flagcdn.com/w80/at.png"},
  {"name": "Jordan", "group": "J", "flag": "https://flagcdn.com/w80/jo.png"},
  {"name": "Portugal", "group": "K", "flag": "https://flagcdn.com/w80/pt.png"},
  {"name": "Congo DR", "group": "K", "flag": "https://flagcdn.com/w80/cd.png"},
  {"name": "Uzbekistan", "group": "K", "flag": "https://flagcdn.com/w80/uz.png"},
  {"name": "Colombia", "group": "K", "flag": "https://flagcdn.com/w80/co.png"},
  {"name": "England", "group": "L", "flag": "https://flagcdn.com/w80/gb-eng.png"},
  {"name": "Croatia", "group": "L", "flag": "https://flagcdn.com/w80/hr.png"},
  {"name": "Ghana", "group": "L", "flag": "https://flagcdn.com/w80/gh.png"},
  {"name": "Panama", "group": "L", "flag": "https://flagcdn.com/w80/pa.png"}
];
